### ISSUE TITLE
Replace announcements with RSS feed to blogger

### ISSUE THREAD

**Issue by dhtdht020** [Disconnect24/dc24.xyz#15]
I have no idea how to mess with RSS or Jekyll

take this one as a suggestion / enhancement

**Comment by Apfel** [comment]
`suggestion / enhancement` != issue :weSmart:

**Comment by dhtdht020** [comment]
enhancement = a tag given for issues that suggest something.

**Comment by spotlightishere** [comment]
We should probably migrate the existing blog over. No use mirroring entirely though - @caution3, you have any thoughts on redirecting entirely?

**Comment by caution3** [comment]
The blog redirects to the Blogger site, unless you guys want to change it, we can design the blog fully after we get Nintendo Channel working.

I'll leave this issue open for now. :)

**Comment by WiiNoMa** [comment]
~test~

**Comment by WiiNoMa** [comment]
boi

**Comment by caution3** [comment]
I'm going to assume that we are currently all happy with the current setup and close this issue. ;p
